stages:
  train:
    #cmd: python3 src/train.py experiment=dogbreed_ex +trainer.log_every_n_steps=5
    cmd: python3 src/train.py experiment=bird_classifier_ex +trainer.log_every_n_steps=1
    deps:
    - configs/experiment/dogbreed_ex.yaml
    - configs/experiment/bird_classifier_ex.yaml
    - src/train.py
    - data
    outs:
    - logs:
        cache: false
  evaluation:
    cmd: python3 src/eval.py data=birddata evaluation=bird_eval
    deps:
    - configs/evaluation/dogbreed_eval.yaml
    - configs/evaluation/bird_eval.yaml
    - configs/data/birddata.yaml
    - configs/data/dogbreed.yaml
    - data
    - src/eval.py
    outs:
    - evaluations:
        cache: false
  inference:
    cmd: python3 src/infer.py data=birddata inference=bird_infer
    deps:
    - configs/data/birddata.yaml
    - configs/data/dogbreed.yaml
    - configs/inference/dogbreed_infer.yaml
    - configs/inference/bird_infer.yaml
    - data
    - src/infer.py
    outs:
    - predictions:
        cache: false
