defaults:
  - eval
  - _self_






model:
  _target_: src.model_builder.timm_classifier.TimmClassifier
  model_name: resnet18
  num_classes: 11

data:
  _target_: src.datamodules.data_module.GenericDataModule
  batch_size: 32
  num_workers: 0

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 1
  accelerator: cpu
  devices: 1

ckpt_path: null

hydra:
  run:
    dir: .

