defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

trainer:
  max_epochs: 1
  accelerator: cpu
  devices: 1

model:
  _target_: pytorch_lightning.LightningModule

data:
  _target_: pytorch_lightning.LightningDataModule

callbacks:
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ${paths.output_dir}/checkpoints
    filename: "best_model"
    save_top_k: 1
    monitor: "val_loss"
    mode: "min"
    save_last: true

test: true

hydra:
  output_subdir: null
  run:
    dir: .
