# @package _global_
defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/launcher: joblib

name: "bird_mobilenetv3_small_hparam"
experiment_name: "bird_mobilenetv3_small_hparam"
optimization_metrics: "test/acc_best"

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
      n_startup_trials: 5
    direction: maximize
    study_name: bird_mobilenetv3_small_hparam_optimization
    storage: null
    n_trials: 5
    n_jobs: 4 
    params:
      model.base_model: choice("mobilenetv3_small_050", "mobilenetv3_small_075", "mobilenetv3_small_100")
      model.num_classes: 11
      model.pretrained: True
      model.learning_rate: choice(1e-4, 3e-4, 1e-3)
      model.weight_decay: choice(1e-5, 1e-4, 1e-3)
      data.batch_size: choice(32, 64, 128)
      regularization.gradient_clipping: choice(0.1, 0.3, 0.5)

  launcher:
    n_jobs: 3
    backend: 'loky'

data:
  batch_size: 32
  image_size: 224

trainer:
  min_epochs: 1
  max_epochs: 1
