# @package _global_
defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/launcher: joblib

name: "bird_classifier_vit_hparam"
experiment_name: "bird_classifier_vit_hparam"
optimization_metrics: "test/acc_best"

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
      n_startup_trials: 4
    direction: maximize
    study_name: bird_vit_hparam_optimization
    storage: null
    n_trials: 30
    n_jobs: 4 
    params:
      model.base_model: choice("vit_tiny_patch16_224")
      model.patch_size: choice(16)
      model.embed_dim: choice(192,384,768)
      model.num_heads: choice(2,3, 8,12)
      model.num_classes: 11
      model.pretrained: choice(False)
      model.learning_rate: choice(1e-4, 5e-4,1e-3,3e-3,1e-2)
      

  launcher:
    n_jobs: 3
    backend: 'loky'

data:
  batch_size: 32

trainer:
  min_epochs: 1
  max_epochs: 10
